namespace Mostruario.View
{
    partial class FrmProdutos
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Panel pnlCabecalho;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Label lblSubtitulo;
        private System.Windows.Forms.Label lblPesquisa;
        private System.Windows.Forms.TextBox txtPesquisa;
        private System.Windows.Forms.Button btnPesquisar;
        private System.Windows.Forms.Label lblQuantidadeRegistros;
        private System.Windows.Forms.DataGridView gridProdutos;
        private System.Windows.Forms.GroupBox grpEdicao;
        private System.Windows.Forms.Label lblModo;
        private System.Windows.Forms.Label lblNome;
        private System.Windows.Forms.TextBox txtNome;
        private System.Windows.Forms.Label lblMarca;
        private System.Windows.Forms.ComboBox cboMarca;
        private System.Windows.Forms.Label lblTipo;
        private System.Windows.Forms.ComboBox cboTipo;
        private System.Windows.Forms.Label lblUnidade;
        private System.Windows.Forms.TextBox txtUnidade;
        private System.Windows.Forms.Label lblPrecoCusto;
        private System.Windows.Forms.NumericUpDown numPrecoCusto;
        private System.Windows.Forms.Label lblPrecoVenda;
        private System.Windows.Forms.NumericUpDown numPrecoVenda;
        private System.Windows.Forms.Label lblQuantidade;
        private System.Windows.Forms.NumericUpDown numQuantidade;
        private System.Windows.Forms.Label lblValidade;
        private System.Windows.Forms.DateTimePicker dtpValidade;
        private System.Windows.Forms.Label lblDescricao;
        private System.Windows.Forms.RichTextBox txtDescricao;
        private System.Windows.Forms.Button btnNovo;
        private System.Windows.Forms.Button btnEditar;
        private System.Windows.Forms.Button btnSalvar;
        private System.Windows.Forms.Button btnExcluir;
        private System.Windows.Forms.Button btnCancelar;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.pnlCabecalho = new System.Windows.Forms.Panel();
            this.lblSubtitulo = new System.Windows.Forms.Label();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblPesquisa = new System.Windows.Forms.Label();
            this.txtPesquisa = new System.Windows.Forms.TextBox();
            this.btnPesquisar = new System.Windows.Forms.Button();
            this.lblQuantidadeRegistros = new System.Windows.Forms.Label();
            this.gridProdutos = new System.Windows.Forms.DataGridView();
            this.grpEdicao = new System.Windows.Forms.GroupBox();
            this.lblModo = new System.Windows.Forms.Label();
            this.lblNome = new System.Windows.Forms.Label();
            this.txtNome = new System.Windows.Forms.TextBox();
            this.lblMarca = new System.Windows.Forms.Label();
            this.cboMarca = new System.Windows.Forms.ComboBox();
            this.lblTipo = new System.Windows.Forms.Label();
            this.cboTipo = new System.Windows.Forms.ComboBox();
            this.lblUnidade = new System.Windows.Forms.Label();
            this.txtUnidade = new System.Windows.Forms.TextBox();
            this.lblPrecoCusto = new System.Windows.Forms.Label();
            this.numPrecoCusto = new System.Windows.Forms.NumericUpDown();
            this.lblPrecoVenda = new System.Windows.Forms.Label();
            this.numPrecoVenda = new System.Windows.Forms.NumericUpDown();
            this.lblQuantidade = new System.Windows.Forms.Label();
            this.numQuantidade = new System.Windows.Forms.NumericUpDown();
            this.lblValidade = new System.Windows.Forms.Label();
            this.dtpValidade = new System.Windows.Forms.DateTimePicker();
            this.lblDescricao = new System.Windows.Forms.Label();
            this.txtDescricao = new System.Windows.Forms.RichTextBox();
            this.btnNovo = new System.Windows.Forms.Button();
            this.btnEditar = new System.Windows.Forms.Button();
            this.btnSalvar = new System.Windows.Forms.Button();
            this.btnExcluir = new System.Windows.Forms.Button();
            this.btnCancelar = new System.Windows.Forms.Button();
            this.pnlCabecalho.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridProdutos)).BeginInit();
            this.grpEdicao.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numPrecoCusto)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numPrecoVenda)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numQuantidade)).BeginInit();
            this.SuspendLayout();
            this.pnlCabecalho.BackColor = System.Drawing.Color.FromArgb(33, 117, 130);
            this.pnlCabecalho.Controls.Add(this.lblSubtitulo);
            this.pnlCabecalho.Controls.Add(this.lblTitulo);
            this.pnlCabecalho.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlCabecalho.Size = new System.Drawing.Size(1084, 78);
            this.lblTitulo.AutoSize = true;
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI Semibold", 20F, System.Drawing.FontStyle.Bold);
            this.lblTitulo.ForeColor = System.Drawing.Color.White;
            this.lblTitulo.Location = new System.Drawing.Point(24, 10);
            this.lblTitulo.Text = "Produtos";
            this.lblSubtitulo.AutoSize = true;
            this.lblSubtitulo.ForeColor = System.Drawing.Color.FromArgb(213, 238, 241);
            this.lblSubtitulo.Location = new System.Drawing.Point(28, 50);
            this.lblSubtitulo.Text = "Mantenha os itens, valores e quantidades do mostruário";
            this.lblPesquisa.AutoSize = true;
            this.lblPesquisa.Location = new System.Drawing.Point(24, 97);
            this.lblPesquisa.Text = "Pesquisar pelo nome";
            this.txtPesquisa.Location = new System.Drawing.Point(24, 118);
            this.txtPesquisa.MaxLength = 40;
            this.txtPesquisa.Name = "txtPesquisa";
            this.txtPesquisa.Size = new System.Drawing.Size(650, 23);
            this.txtPesquisa.TabIndex = 0;
            this.btnPesquisar.BackColor = System.Drawing.Color.FromArgb(33, 117, 130);
            this.btnPesquisar.FlatAppearance.BorderSize = 0;
            this.btnPesquisar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnPesquisar.ForeColor = System.Drawing.Color.White;
            this.btnPesquisar.Location = new System.Drawing.Point(686, 116);
            this.btnPesquisar.Name = "btnPesquisar";
            this.btnPesquisar.Size = new System.Drawing.Size(110, 27);
            this.btnPesquisar.TabIndex = 1;
            this.btnPesquisar.Text = "Pesquisar";
            this.btnPesquisar.UseVisualStyleBackColor = false;
            this.btnPesquisar.Click += new System.EventHandler(this.btnPesquisar_Click);
            this.lblQuantidadeRegistros.AutoSize = true;
            this.lblQuantidadeRegistros.ForeColor = System.Drawing.Color.DimGray;
            this.lblQuantidadeRegistros.Location = new System.Drawing.Point(24, 151);
            this.lblQuantidadeRegistros.Text = "0 produto(s) encontrado(s)";
            this.gridProdutos.AllowUserToAddRows = false;
            this.gridProdutos.AllowUserToDeleteRows = false;
            this.gridProdutos.BackgroundColor = System.Drawing.Color.White;
            this.gridProdutos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridProdutos.Location = new System.Drawing.Point(24, 174);
            this.gridProdutos.MultiSelect = false;
            this.gridProdutos.Name = "gridProdutos";
            this.gridProdutos.ReadOnly = true;
            this.gridProdutos.RowHeadersVisible = false;
            this.gridProdutos.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.gridProdutos.Size = new System.Drawing.Size(1036, 230);
            this.gridProdutos.TabIndex = 2;
            this.gridProdutos.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.gridProdutos_CellDoubleClick);
            this.grpEdicao.Controls.Add(this.lblModo);
            this.grpEdicao.Controls.Add(this.lblNome);
            this.grpEdicao.Controls.Add(this.txtNome);
            this.grpEdicao.Controls.Add(this.lblMarca);
            this.grpEdicao.Controls.Add(this.cboMarca);
            this.grpEdicao.Controls.Add(this.lblTipo);
            this.grpEdicao.Controls.Add(this.cboTipo);
            this.grpEdicao.Controls.Add(this.lblUnidade);
            this.grpEdicao.Controls.Add(this.txtUnidade);
            this.grpEdicao.Controls.Add(this.lblPrecoCusto);
            this.grpEdicao.Controls.Add(this.numPrecoCusto);
            this.grpEdicao.Controls.Add(this.lblPrecoVenda);
            this.grpEdicao.Controls.Add(this.numPrecoVenda);
            this.grpEdicao.Controls.Add(this.lblQuantidade);
            this.grpEdicao.Controls.Add(this.numQuantidade);
            this.grpEdicao.Controls.Add(this.lblValidade);
            this.grpEdicao.Controls.Add(this.dtpValidade);
            this.grpEdicao.Controls.Add(this.lblDescricao);
            this.grpEdicao.Controls.Add(this.txtDescricao);
            this.grpEdicao.Location = new System.Drawing.Point(24, 418);
            this.grpEdicao.Name = "grpEdicao";
            this.grpEdicao.Size = new System.Drawing.Size(1036, 245);
            this.grpEdicao.TabIndex = 3;
            this.grpEdicao.TabStop = false;
            this.lblModo.AutoSize = true;
            this.lblModo.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.lblModo.ForeColor = System.Drawing.Color.FromArgb(33, 117, 130);
            this.lblModo.Location = new System.Drawing.Point(14, 20);
            this.lblModo.Text = "Novo produto";
            this.lblNome.AutoSize = true;
            this.lblNome.Location = new System.Drawing.Point(14, 50);
            this.lblNome.Text = "Nome *";
            this.txtNome.Location = new System.Drawing.Point(14, 70);
            this.txtNome.MaxLength = 40;
            this.txtNome.Name = "txtNome";
            this.txtNome.Size = new System.Drawing.Size(250, 23);
            this.txtNome.TabIndex = 0;
            this.lblMarca.AutoSize = true;
            this.lblMarca.Location = new System.Drawing.Point(280, 50);
            this.lblMarca.Text = "Marca *";
            this.cboMarca.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboMarca.FormattingEnabled = true;
            this.cboMarca.Location = new System.Drawing.Point(280, 70);
            this.cboMarca.Name = "cboMarca";
            this.cboMarca.Size = new System.Drawing.Size(220, 23);
            this.cboMarca.TabIndex = 1;
            this.lblTipo.AutoSize = true;
            this.lblTipo.Location = new System.Drawing.Point(516, 50);
            this.lblTipo.Text = "Tipo de produto *";
            this.cboTipo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTipo.FormattingEnabled = true;
            this.cboTipo.Location = new System.Drawing.Point(516, 70);
            this.cboTipo.Name = "cboTipo";
            this.cboTipo.Size = new System.Drawing.Size(220, 23);
            this.cboTipo.TabIndex = 2;
            this.lblUnidade.AutoSize = true;
            this.lblUnidade.Location = new System.Drawing.Point(752, 50);
            this.lblUnidade.Text = "Unidade *";
            this.txtUnidade.Location = new System.Drawing.Point(752, 70);
            this.txtUnidade.MaxLength = 10;
            this.txtUnidade.Name = "txtUnidade";
            this.txtUnidade.Size = new System.Drawing.Size(100, 23);
            this.txtUnidade.TabIndex = 3;
            this.lblPrecoCusto.AutoSize = true;
            this.lblPrecoCusto.Location = new System.Drawing.Point(14, 106);
            this.lblPrecoCusto.Text = "Preço de custo";
            this.numPrecoCusto.DecimalPlaces = 2;
            this.numPrecoCusto.Location = new System.Drawing.Point(14, 126);
            this.numPrecoCusto.Maximum = 99999999.99M;
            this.numPrecoCusto.Name = "numPrecoCusto";
            this.numPrecoCusto.Size = new System.Drawing.Size(150, 23);
            this.numPrecoCusto.TabIndex = 4;
            this.numPrecoCusto.ThousandsSeparator = true;
            this.lblPrecoVenda.AutoSize = true;
            this.lblPrecoVenda.Location = new System.Drawing.Point(180, 106);
            this.lblPrecoVenda.Text = "Preço de venda";
            this.numPrecoVenda.DecimalPlaces = 2;
            this.numPrecoVenda.Location = new System.Drawing.Point(180, 126);
            this.numPrecoVenda.Maximum = 99999999.99M;
            this.numPrecoVenda.Name = "numPrecoVenda";
            this.numPrecoVenda.Size = new System.Drawing.Size(150, 23);
            this.numPrecoVenda.TabIndex = 5;
            this.numPrecoVenda.ThousandsSeparator = true;
            this.lblQuantidade.AutoSize = true;
            this.lblQuantidade.Location = new System.Drawing.Point(346, 106);
            this.lblQuantidade.Text = "Quantidade";
            this.numQuantidade.Location = new System.Drawing.Point(346, 126);
            this.numQuantidade.Maximum = new decimal(new int[] { 1000000, 0, 0, 0 });
            this.numQuantidade.Name = "numQuantidade";
            this.numQuantidade.Size = new System.Drawing.Size(130, 23);
            this.numQuantidade.TabIndex = 6;
            this.numQuantidade.ThousandsSeparator = true;
            this.lblValidade.AutoSize = true;
            this.lblValidade.Location = new System.Drawing.Point(492, 106);
            this.lblValidade.Text = "Validade (marque se houver)";
            this.dtpValidade.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpValidade.Location = new System.Drawing.Point(492, 126);
            this.dtpValidade.Name = "dtpValidade";
            this.dtpValidade.ShowCheckBox = true;
            this.dtpValidade.Size = new System.Drawing.Size(180, 23);
            this.dtpValidade.TabIndex = 7;
            this.lblDescricao.AutoSize = true;
            this.lblDescricao.Location = new System.Drawing.Point(14, 165);
            this.lblDescricao.Text = "Descrição *";
            this.txtDescricao.Location = new System.Drawing.Point(14, 185);
            this.txtDescricao.Name = "txtDescricao";
            this.txtDescricao.Size = new System.Drawing.Size(1006, 45);
            this.txtDescricao.TabIndex = 8;
            this.txtDescricao.Text = "";
            this.btnNovo.Location = new System.Drawing.Point(24, 680);
            this.btnNovo.Name = "btnNovo";
            this.btnNovo.Size = new System.Drawing.Size(95, 32);
            this.btnNovo.TabIndex = 4;
            this.btnNovo.Text = "Novo";
            this.btnNovo.Click += new System.EventHandler(this.btnNovo_Click);
            this.btnEditar.Location = new System.Drawing.Point(127, 680);
            this.btnEditar.Name = "btnEditar";
            this.btnEditar.Size = new System.Drawing.Size(125, 32);
            this.btnEditar.TabIndex = 5;
            this.btnEditar.Text = "Editar selecionado";
            this.btnEditar.Click += new System.EventHandler(this.btnEditar_Click);
            this.btnSalvar.BackColor = System.Drawing.Color.FromArgb(33, 117, 130);
            this.btnSalvar.FlatAppearance.BorderSize = 0;
            this.btnSalvar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSalvar.ForeColor = System.Drawing.Color.White;
            this.btnSalvar.Location = new System.Drawing.Point(260, 680);
            this.btnSalvar.Name = "btnSalvar";
            this.btnSalvar.Size = new System.Drawing.Size(95, 32);
            this.btnSalvar.TabIndex = 6;
            this.btnSalvar.Text = "Salvar";
            this.btnSalvar.UseVisualStyleBackColor = false;
            this.btnSalvar.Click += new System.EventHandler(this.btnSalvar_Click);
            this.btnExcluir.ForeColor = System.Drawing.Color.Maroon;
            this.btnExcluir.Location = new System.Drawing.Point(857, 680);
            this.btnExcluir.Name = "btnExcluir";
            this.btnExcluir.Size = new System.Drawing.Size(95, 32);
            this.btnExcluir.TabIndex = 7;
            this.btnExcluir.Text = "Excluir";
            this.btnExcluir.Click += new System.EventHandler(this.btnExcluir_Click);
            this.btnCancelar.Location = new System.Drawing.Point(960, 680);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(100, 32);
            this.btnCancelar.TabIndex = 8;
            this.btnCancelar.Text = "Cancelar";
            this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(245, 248, 248);
            this.ClientSize = new System.Drawing.Size(1084, 735);
            this.Controls.Add(this.btnCancelar);
            this.Controls.Add(this.btnExcluir);
            this.Controls.Add(this.btnSalvar);
            this.Controls.Add(this.btnEditar);
            this.Controls.Add(this.btnNovo);
            this.Controls.Add(this.grpEdicao);
            this.Controls.Add(this.gridProdutos);
            this.Controls.Add(this.lblQuantidadeRegistros);
            this.Controls.Add(this.btnPesquisar);
            this.Controls.Add(this.txtPesquisa);
            this.Controls.Add(this.lblPesquisa);
            this.Controls.Add(this.pnlCabecalho);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "FrmProdutos";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Gerenciar produtos";
            this.Load += new System.EventHandler(this.FrmProdutos_Load);
            this.pnlCabecalho.ResumeLayout(false);
            this.pnlCabecalho.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridProdutos)).EndInit();
            this.grpEdicao.ResumeLayout(false);
            this.grpEdicao.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numPrecoCusto)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numPrecoVenda)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numQuantidade)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
