namespace Mostruario.View
{
    partial class FrmTiposProduto
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Panel pnlCabecalho;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Label lblSubtitulo;
        private System.Windows.Forms.Label lblPesquisa;
        private System.Windows.Forms.TextBox txtPesquisa;
        private System.Windows.Forms.Button btnPesquisar;
        private System.Windows.Forms.Label lblQuantidade;
        private System.Windows.Forms.DataGridView gridTipos;
        private System.Windows.Forms.GroupBox grpEdicao;
        private System.Windows.Forms.Label lblModo;
        private System.Windows.Forms.Label lblNome;
        private System.Windows.Forms.TextBox txtNome;
        private System.Windows.Forms.Button btnNovo;
        private System.Windows.Forms.Button btnEditar;
        private System.Windows.Forms.Button btnSalvar;
        private System.Windows.Forms.Button btnExcluir;
        private System.Windows.Forms.Button btnCancelar;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.pnlCabecalho = new System.Windows.Forms.Panel();
            this.lblSubtitulo = new System.Windows.Forms.Label();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblPesquisa = new System.Windows.Forms.Label();
            this.txtPesquisa = new System.Windows.Forms.TextBox();
            this.btnPesquisar = new System.Windows.Forms.Button();
            this.lblQuantidade = new System.Windows.Forms.Label();
            this.gridTipos = new System.Windows.Forms.DataGridView();
            this.grpEdicao = new System.Windows.Forms.GroupBox();
            this.lblModo = new System.Windows.Forms.Label();
            this.lblNome = new System.Windows.Forms.Label();
            this.txtNome = new System.Windows.Forms.TextBox();
            this.btnNovo = new System.Windows.Forms.Button();
            this.btnEditar = new System.Windows.Forms.Button();
            this.btnSalvar = new System.Windows.Forms.Button();
            this.btnExcluir = new System.Windows.Forms.Button();
            this.btnCancelar = new System.Windows.Forms.Button();
            this.pnlCabecalho.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridTipos)).BeginInit();
            this.grpEdicao.SuspendLayout();
            this.SuspendLayout();
            this.pnlCabecalho.BackColor = System.Drawing.Color.FromArgb(96, 83, 135);
            this.pnlCabecalho.Controls.Add(this.lblSubtitulo);
            this.pnlCabecalho.Controls.Add(this.lblTitulo);
            this.pnlCabecalho.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlCabecalho.Size = new System.Drawing.Size(784, 78);
            this.lblTitulo.AutoSize = true;
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI Semibold", 20F, System.Drawing.FontStyle.Bold);
            this.lblTitulo.ForeColor = System.Drawing.Color.White;
            this.lblTitulo.Location = new System.Drawing.Point(24, 10);
            this.lblTitulo.Text = "Tipos de produto";
            this.lblSubtitulo.AutoSize = true;
            this.lblSubtitulo.ForeColor = System.Drawing.Color.FromArgb(232, 227, 241);
            this.lblSubtitulo.Location = new System.Drawing.Point(28, 50);
            this.lblSubtitulo.Text = "Crie categorias simples para organizar o mostruário";
            this.lblPesquisa.AutoSize = true;
            this.lblPesquisa.Location = new System.Drawing.Point(24, 97);
            this.lblPesquisa.Text = "Pesquisar pelo nome";
            this.txtPesquisa.Location = new System.Drawing.Point(24, 118);
            this.txtPesquisa.MaxLength = 40;
            this.txtPesquisa.Name = "txtPesquisa";
            this.txtPesquisa.Size = new System.Drawing.Size(500, 23);
            this.txtPesquisa.TabIndex = 0;
            this.btnPesquisar.BackColor = System.Drawing.Color.FromArgb(96, 83, 135);
            this.btnPesquisar.FlatAppearance.BorderSize = 0;
            this.btnPesquisar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnPesquisar.ForeColor = System.Drawing.Color.White;
            this.btnPesquisar.Location = new System.Drawing.Point(536, 116);
            this.btnPesquisar.Name = "btnPesquisar";
            this.btnPesquisar.Size = new System.Drawing.Size(110, 27);
            this.btnPesquisar.TabIndex = 1;
            this.btnPesquisar.Text = "Pesquisar";
            this.btnPesquisar.UseVisualStyleBackColor = false;
            this.btnPesquisar.Click += new System.EventHandler(this.btnPesquisar_Click);
            this.lblQuantidade.AutoSize = true;
            this.lblQuantidade.ForeColor = System.Drawing.Color.DimGray;
            this.lblQuantidade.Location = new System.Drawing.Point(24, 151);
            this.lblQuantidade.Text = "0 tipo(s) encontrado(s)";
            this.gridTipos.AllowUserToAddRows = false;
            this.gridTipos.AllowUserToDeleteRows = false;
            this.gridTipos.BackgroundColor = System.Drawing.Color.White;
            this.gridTipos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.gridTipos.Location = new System.Drawing.Point(24, 174);
            this.gridTipos.MultiSelect = false;
            this.gridTipos.Name = "gridTipos";
            this.gridTipos.ReadOnly = true;
            this.gridTipos.RowHeadersVisible = false;
            this.gridTipos.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.gridTipos.Size = new System.Drawing.Size(736, 205);
            this.gridTipos.TabIndex = 2;
            this.gridTipos.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.gridTipos_CellDoubleClick);
            this.grpEdicao.Controls.Add(this.lblModo);
            this.grpEdicao.Controls.Add(this.lblNome);
            this.grpEdicao.Controls.Add(this.txtNome);
            this.grpEdicao.Location = new System.Drawing.Point(24, 393);
            this.grpEdicao.Name = "grpEdicao";
            this.grpEdicao.Size = new System.Drawing.Size(736, 110);
            this.grpEdicao.TabIndex = 3;
            this.grpEdicao.TabStop = false;
            this.lblModo.AutoSize = true;
            this.lblModo.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.lblModo.ForeColor = System.Drawing.Color.FromArgb(96, 83, 135);
            this.lblModo.Location = new System.Drawing.Point(14, 20);
            this.lblModo.Text = "Novo tipo de produto";
            this.lblNome.AutoSize = true;
            this.lblNome.Location = new System.Drawing.Point(14, 50);
            this.lblNome.Text = "Nome *";
            this.txtNome.Location = new System.Drawing.Point(14, 71);
            this.txtNome.MaxLength = 40;
            this.txtNome.Name = "txtNome";
            this.txtNome.Size = new System.Drawing.Size(430, 23);
            this.txtNome.TabIndex = 0;
            this.btnNovo.Location = new System.Drawing.Point(24, 522);
            this.btnNovo.Name = "btnNovo";
            this.btnNovo.Size = new System.Drawing.Size(90, 32);
            this.btnNovo.TabIndex = 4;
            this.btnNovo.Text = "Novo";
            this.btnNovo.Click += new System.EventHandler(this.btnNovo_Click);
            this.btnEditar.Location = new System.Drawing.Point(122, 522);
            this.btnEditar.Name = "btnEditar";
            this.btnEditar.Size = new System.Drawing.Size(120, 32);
            this.btnEditar.TabIndex = 5;
            this.btnEditar.Text = "Editar selecionado";
            this.btnEditar.Click += new System.EventHandler(this.btnEditar_Click);
            this.btnSalvar.BackColor = System.Drawing.Color.FromArgb(96, 83, 135);
            this.btnSalvar.FlatAppearance.BorderSize = 0;
            this.btnSalvar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSalvar.ForeColor = System.Drawing.Color.White;
            this.btnSalvar.Location = new System.Drawing.Point(250, 522);
            this.btnSalvar.Name = "btnSalvar";
            this.btnSalvar.Size = new System.Drawing.Size(90, 32);
            this.btnSalvar.TabIndex = 6;
            this.btnSalvar.Text = "Salvar";
            this.btnSalvar.UseVisualStyleBackColor = false;
            this.btnSalvar.Click += new System.EventHandler(this.btnSalvar_Click);
            this.btnExcluir.ForeColor = System.Drawing.Color.Maroon;
            this.btnExcluir.Location = new System.Drawing.Point(572, 522);
            this.btnExcluir.Name = "btnExcluir";
            this.btnExcluir.Size = new System.Drawing.Size(90, 32);
            this.btnExcluir.TabIndex = 7;
            this.btnExcluir.Text = "Excluir";
            this.btnExcluir.Click += new System.EventHandler(this.btnExcluir_Click);
            this.btnCancelar.Location = new System.Drawing.Point(670, 522);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(90, 32);
            this.btnCancelar.TabIndex = 8;
            this.btnCancelar.Text = "Cancelar";
            this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(245, 248, 248);
            this.ClientSize = new System.Drawing.Size(784, 578);
            this.Controls.Add(this.btnCancelar);
            this.Controls.Add(this.btnExcluir);
            this.Controls.Add(this.btnSalvar);
            this.Controls.Add(this.btnEditar);
            this.Controls.Add(this.btnNovo);
            this.Controls.Add(this.grpEdicao);
            this.Controls.Add(this.gridTipos);
            this.Controls.Add(this.lblQuantidade);
            this.Controls.Add(this.btnPesquisar);
            this.Controls.Add(this.txtPesquisa);
            this.Controls.Add(this.lblPesquisa);
            this.Controls.Add(this.pnlCabecalho);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "FrmTiposProduto";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Gerenciar tipos de produto";
            this.Load += new System.EventHandler(this.FrmTiposProduto_Load);
            this.pnlCabecalho.ResumeLayout(false);
            this.pnlCabecalho.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridTipos)).EndInit();
            this.grpEdicao.ResumeLayout(false);
            this.grpEdicao.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
